# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e7cef4789ef0fba17ac956b1d7aa406b90add95b595e3002eb4ee8aa103b3cb5835dea885071300056c3e330b9766f3b05029248890dc45f7494baffd56167

test:
  secret_key_base: b80858a5efe379974a31e6c11c9cfbdc2d2be91ed33e60edecf3f474c94e7e76dcd13b3c603b99427966bda7fe28690feda0316511b94e7f804053ec80f19581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
